# 事前準備: リポジトリのSettings > Actions > General > Workflow permissionsを
# Read repository contents permission から Read and write permissions に変更する

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  notice-assign:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.actor }} was assigned to this pull request.
